# important that randphrase is in PATH, dicter does not hardcode its path.
# mise will add the debug folder to the path, if mise is not enabled use
# install to run and make sure ~/.local/bin is in your path
#
# darrell - renedupas@proton.me
#
# welcome to dicter
#
[env]
_.path = ["{{config_root}}/target/debug"]

[tasks.00_clean]
run = "rm -rf target"

[tasks.01_run]
run = """
cargo run --bin dicter -- \
  --interval 1 \
  --dict freedict-fra-eng
"""

[tasks.02_debug]
run = """
DEBUG=1 cargo run --bin dicter -- \
  --interval 1 \
  --dict freedict-fra-eng
"""

[tasks.03_build-release]
run = "cargo build --release --workspace"

[tasks.04_run_scroller]
run = """
cargo run --bin dicter -- --interval 10 \
  | cargo run --bin scroller -- \
    --width 40 \
    --interval_ms 250 \
    --duration_ms 10000
"""

[tasks.run_slowcat]
run = """
printf "the quick brown fox jumped over the lazy dog\n" \
  | cargo run --bin slowcat -- \
    --linelen 10 \
    --interval 2 \
    --no-repeat
"""

[tasks.run_slowcat_with_scroller]
run = """
  echo "the quick brown fox jumped over the lazy dog" \
  | cargo run --bin slowcat -- --interval 4 --repeat true \
  | cargo run --bin scroller -- --width 14 --interval_ms 50  \
    --duration_ms 2700 --delay 0 --mode marquee
"""
[tasks.run_slowcat_with_reader]
# notice there is no duration_ms with reader mode, it is calculated based
# on the length of the line and interval, I am unsure about how fast or slow
# slowcat needs to be.
run = """
  cat ./mise.toml \
  | cargo run --bin slowcat -- --interval 1  \
  | cargo run --bin scroller -- --width 20 --interval_ms 40  \
  --y 0 --mode reader
"""




[tasks.install]
depends = "03_build-release"
run = """
pkill dicter || true
pkill randphrase || true
pkill waybar || true
pkill scroller || true
pkill slowcat || true
cp target/release/dicter ~/.local/bin
cp target/release/randphrase ~/.local/bin
cp target/release/scroller ~/.local/bin
cp target/release/slowcat ~/.local/bin
"""

[tasks.time-ticker]
# duration can be calculated in 3 ways, trial and error, timeit without repeat,
# calculating the length of the input string and how far it needs to scroll
# times the interval, the first is easiest.
# Example: string length 22, must travel the width of 40, so 62, with an
# interval of 200 is around 12400, then of course there is the padding which
# i forgot to mention, you can see why trial and error is best, just do
# one loop and see where it ends and subtract or add the interval to get one
# cycle
run = """
nu -c '
print (ansi -e '?25l') # hide cursor
loop {
clear
  date now | to text | str substring 0..-16
  | scroller --width 40 --interval_ms 200 --duration_ms 12400 --delay 0 --x 5 --y 5 --nopad --mode marquee }
'
"""
